// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dadaxiaoxiao/cron-job/internal/grpc"
	"github.com/dadaxiaoxiao/cron-job/internal/repository"
	"github.com/dadaxiaoxiao/cron-job/internal/repository/dao"
	"github.com/dadaxiaoxiao/cron-job/internal/service"
	"github.com/dadaxiaoxiao/cron-job/ioc"
	"github.com/dadaxiaoxiao/go-pkg/customserver"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *customserver.App {
	client := ioc.InitEtcdClient()
	db := ioc.InitDB()
	jobDAO := dao.NewGORMJobDAO(db)
	cronJobRepository := repository.NewPreemptCronJobRepository(jobDAO)
	logger := ioc.InitLogger()
	cronJobService := service.NewCronJobService(cronJobRepository, logger)
	cronJobServiceServer := grpc.NewCronJobServiceServer(cronJobService)
	cmdable := ioc.InitRedis()
	server := ioc.InitGRPCServer(client, cronJobServiceServer, cmdable, logger)
	app := &customserver.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var thirdPartyProvider = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitEtcdClient, ioc.InitLogger, ioc.InitOTEL)
