db:
  dsn: "root:root@tcp(localhost:13316)/demo_cronjob"

grpc:
  server:
    port: 8010
    etcdTTL: 60

etcd:
  endpoints:
    - "localhost:12379"

logger:
  filename: "d:\\appcache\\elasticsearch\\logs\\cronjob.log"
  maxsize: 50
  maxBackups: 3
  maxAge: 7

opentelemetry:
  serviceName: "demo"
  serviceVersion: "v0.0.1"

zipkin:
  collectorURL: "http://localhost:9411/api/v2/spans"

prometheus:
  listenPort: ":8081"

remoteProvider:
  provider: "etcd3"
  endpoint: "http://127.0.0.1:12379"
  path: "/cron_job"